<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>centeredOrigin</key>
	<true/>
	<key>currentResolution</key>
	<integer>0</integer>
	<key>currentSequenceId</key>
	<integer>1</integer>
	<key>fileType</key>
	<string>Redream</string>
	<key>fileVersion</key>
	<integer>1</integer>
	<key>guides</key>
	<array/>
	<key>nodeGraph</key>
	<dict>
		<key>animatedProperties</key>
		<dict/>
		<key>baseClass</key>
		<string>CCNode</string>
		<key>children</key>
		<array>
			<dict>
				<key>animatedProperties</key>
				<dict>
					<key>0</key>
					<dict>
						<key>visible</key>
						<dict>
							<key>keyframes</key>
							<array>
								<dict>
									<key>easing</key>
									<dict>
										<key>type</key>
										<integer>0</integer>
									</dict>
									<key>name</key>
									<string>visible</string>
									<key>pathValues</key>
									<array/>
									<key>time</key>
									<real>0.0</real>
									<key>type</key>
									<integer>1</integer>
									<key>value</key>
									<true/>
								</dict>
							</array>
							<key>name</key>
							<string>visible</string>
							<key>type</key>
							<integer>1</integer>
						</dict>
					</dict>
				</dict>
				<key>baseClass</key>
				<string>CCNode</string>
				<key>children</key>
				<array>
					<dict>
						<key>animatedProperties</key>
						<dict/>
						<key>baseClass</key>
						<string>CCScale9Sprite</string>
						<key>children</key>
						<array/>
						<key>customClass</key>
						<string></string>
						<key>customProperties</key>
						<array/>
						<key>displayName</key>
						<string>时效组_底板左</string>
						<key>expand</key>
						<true/>
						<key>hidden</key>
						<false/>
						<key>locked</key>
						<false/>
						<key>memberVarAssignmentName</key>
						<string></string>
						<key>memberVarAssignmentType</key>
						<integer>0</integer>
						<key>nodeColorTag</key>
						<integer>0</integer>
						<key>properties</key>
						<array>
							<dict>
								<key>name</key>
								<string>position</string>
								<key>type</key>
								<string>Position</string>
								<key>value</key>
								<array>
									<real>0.0</real>
									<real>0.0</real>
									<integer>0</integer>
									<integer>2</integer>
									<integer>2</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>anchorPoint</string>
								<key>type</key>
								<string>Point</string>
								<key>value</key>
								<array>
									<real>1.0</real>
									<real>0.5</real>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>opacity</string>
								<key>type</key>
								<string>Byte</string>
								<key>value</key>
								<integer>255</integer>
							</dict>
							<dict>
								<key>name</key>
								<string>color</string>
								<key>type</key>
								<string>Color3</string>
								<key>value</key>
								<array>
									<integer>255</integer>
									<integer>255</integer>
									<integer>255</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>spriteFrame</string>
								<key>type</key>
								<string>SpriteFrame</string>
								<key>value</key>
								<array>
									<string>钟表_指针动画.plist</string>
									<string>钟表_指针动画_时效组_底板.png</string>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>preferedSize</string>
								<key>type</key>
								<string>Size</string>
								<key>value</key>
								<array>
									<real>158.0</real>
									<real>95.0</real>
									<integer>0</integer>
									<integer>0</integer>
									<false/>
									<false/>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>insetLeft</string>
								<key>type</key>
								<string>Float</string>
								<key>value</key>
								<real>55.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>insetTop</string>
								<key>type</key>
								<string>Float</string>
								<key>value</key>
								<real>5.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>insetRight</string>
								<key>type</key>
								<string>Float</string>
								<key>value</key>
								<real>1.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>insetBottom</string>
								<key>type</key>
								<string>Float</string>
								<key>value</key>
								<real>5.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>previewInset</string>
								<key>type</key>
								<string>Check</string>
								<key>value</key>
								<true/>
							</dict>
						</array>
						<key>seqExpanded</key>
						<false/>
						<key>uniqueNodeId</key>
						<integer>674645422</integer>
					</dict>
					<dict>
						<key>animatedProperties</key>
						<dict/>
						<key>baseClass</key>
						<string>CCScale9Sprite</string>
						<key>children</key>
						<array/>
						<key>customClass</key>
						<string></string>
						<key>customProperties</key>
						<array/>
						<key>displayName</key>
						<string>时效组_底板右</string>
						<key>expand</key>
						<true/>
						<key>hidden</key>
						<false/>
						<key>locked</key>
						<false/>
						<key>memberVarAssignmentName</key>
						<string></string>
						<key>memberVarAssignmentType</key>
						<integer>0</integer>
						<key>nodeColorTag</key>
						<integer>0</integer>
						<key>properties</key>
						<array>
							<dict>
								<key>name</key>
								<string>position</string>
								<key>type</key>
								<string>Position</string>
								<key>value</key>
								<array>
									<real>0.0</real>
									<real>0.0</real>
									<integer>0</integer>
									<integer>2</integer>
									<integer>2</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>anchorPoint</string>
								<key>type</key>
								<string>Point</string>
								<key>value</key>
								<array>
									<real>1.0</real>
									<real>0.5</real>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>scale</string>
								<key>type</key>
								<string>ScaleLock</string>
								<key>value</key>
								<array>
									<real>-1.0</real>
									<real>1.0</real>
									<false/>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>opacity</string>
								<key>type</key>
								<string>Byte</string>
								<key>value</key>
								<integer>255</integer>
							</dict>
							<dict>
								<key>name</key>
								<string>color</string>
								<key>type</key>
								<string>Color3</string>
								<key>value</key>
								<array>
									<integer>255</integer>
									<integer>255</integer>
									<integer>255</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>spriteFrame</string>
								<key>type</key>
								<string>SpriteFrame</string>
								<key>value</key>
								<array>
									<string>钟表_指针动画.plist</string>
									<string>钟表_指针动画_时效组_底板.png</string>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>preferedSize</string>
								<key>type</key>
								<string>Size</string>
								<key>value</key>
								<array>
									<real>158.0</real>
									<real>95.0</real>
									<integer>0</integer>
									<integer>0</integer>
									<false/>
									<false/>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>insetLeft</string>
								<key>type</key>
								<string>Float</string>
								<key>value</key>
								<real>55.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>insetTop</string>
								<key>type</key>
								<string>Float</string>
								<key>value</key>
								<real>5.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>insetRight</string>
								<key>type</key>
								<string>Float</string>
								<key>value</key>
								<real>1.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>insetBottom</string>
								<key>type</key>
								<string>Float</string>
								<key>value</key>
								<real>5.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>previewInset</string>
								<key>type</key>
								<string>Check</string>
								<key>value</key>
								<true/>
							</dict>
						</array>
						<key>seqExpanded</key>
						<false/>
						<key>uniqueNodeId</key>
						<integer>578027219</integer>
					</dict>
					<dict>
						<key>animatedProperties</key>
						<dict>
							<key>0</key>
							<dict>
								<key>scale</key>
								<dict>
									<key>keyframes</key>
									<array>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>1</integer>
											</dict>
											<key>name</key>
											<string>scale</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>4.2666669</real>
											<key>type</key>
											<integer>4</integer>
											<key>value</key>
											<array>
												<real>1.0</real>
												<real>1.0</real>
											</array>
										</dict>
									</array>
									<key>name</key>
									<string>scale</string>
									<key>type</key>
									<integer>4</integer>
								</dict>
							</dict>
						</dict>
						<key>baseClass</key>
						<string>CCSprite</string>
						<key>children</key>
						<array/>
						<key>customClass</key>
						<string></string>
						<key>customProperties</key>
						<array/>
						<key>displayName</key>
						<string>图标_时钟</string>
						<key>expand</key>
						<false/>
						<key>hidden</key>
						<false/>
						<key>locked</key>
						<false/>
						<key>memberVarAssignmentName</key>
						<string></string>
						<key>memberVarAssignmentType</key>
						<integer>0</integer>
						<key>nodeColorTag</key>
						<integer>0</integer>
						<key>properties</key>
						<array>
							<dict>
								<key>name</key>
								<string>position</string>
								<key>type</key>
								<string>Position</string>
								<key>value</key>
								<array>
									<integer>0</integer>
									<integer>0</integer>
									<integer>0</integer>
									<integer>0</integer>
									<integer>0</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>scale</string>
								<key>type</key>
								<string>ScaleLock</string>
								<key>value</key>
								<array>
									<real>1.0</real>
									<real>1.0</real>
									<false/>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>opacity</string>
								<key>type</key>
								<string>Byte</string>
								<key>value</key>
								<integer>255</integer>
							</dict>
							<dict>
								<key>name</key>
								<string>color</string>
								<key>type</key>
								<string>Color3</string>
								<key>value</key>
								<array>
									<integer>255</integer>
									<integer>255</integer>
									<integer>255</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>displayFrame</string>
								<key>type</key>
								<string>SpriteFrame</string>
								<key>value</key>
								<array>
									<string>钟表_指针动画.plist</string>
									<string>钟表_指针动画_图标_时钟.png</string>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>useMaterial</string>
								<key>type</key>
								<string>Check</string>
								<key>value</key>
								<false/>
							</dict>
							<dict>
								<key>name</key>
								<string>blendFunc</string>
								<key>type</key>
								<string>Blendmode</string>
								<key>value</key>
								<array>
									<integer>1</integer>
									<integer>771</integer>
								</array>
							</dict>
						</array>
						<key>seqExpanded</key>
						<false/>
						<key>uniqueNodeId</key>
						<integer>791452776</integer>
					</dict>
					<dict>
						<key>animatedProperties</key>
						<dict>
							<key>0</key>
							<dict>
								<key>rotation</key>
								<dict>
									<key>keyframes</key>
									<array>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>1</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>0.0</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>0.0</real>
										</dict>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>12</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>0.0</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>0.0</real>
										</dict>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>1</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>0.5</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>90.0</real>
										</dict>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>12</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>1.0666667</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>90.0</real>
										</dict>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>1</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>1.6</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>180.0</real>
										</dict>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>12</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>2.2</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>180.0</real>
										</dict>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>1</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>2.7</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>270.0</real>
										</dict>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>12</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>3.2333333</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>270.0</real>
										</dict>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>1</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>3.8</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>360.0</real>
										</dict>
									</array>
									<key>name</key>
									<string>rotation</string>
									<key>type</key>
									<integer>2</integer>
								</dict>
							</dict>
						</dict>
						<key>baseClass</key>
						<string>CCSprite</string>
						<key>children</key>
						<array/>
						<key>customClass</key>
						<string></string>
						<key>customProperties</key>
						<array/>
						<key>displayName</key>
						<string>指针</string>
						<key>expand</key>
						<true/>
						<key>hidden</key>
						<false/>
						<key>locked</key>
						<false/>
						<key>memberVarAssignmentName</key>
						<string></string>
						<key>memberVarAssignmentType</key>
						<integer>0</integer>
						<key>nodeColorTag</key>
						<integer>0</integer>
						<key>properties</key>
						<array>
							<dict>
								<key>name</key>
								<string>visible</string>
								<key>type</key>
								<string>Check</string>
								<key>value</key>
								<true/>
							</dict>
							<dict>
								<key>name</key>
								<string>position</string>
								<key>type</key>
								<string>Position</string>
								<key>value</key>
								<array>
									<real>-2.0</real>
									<real>-6.0</real>
									<integer>0</integer>
									<integer>0</integer>
									<integer>0</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>anchorPoint</string>
								<key>type</key>
								<string>Point</string>
								<key>value</key>
								<array>
									<real>0.5</real>
									<real>0.3</real>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>rotation</string>
								<key>type</key>
								<string>Degrees</string>
								<key>value</key>
								<real>0.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>opacity</string>
								<key>type</key>
								<string>Byte</string>
								<key>value</key>
								<integer>255</integer>
							</dict>
							<dict>
								<key>name</key>
								<string>color</string>
								<key>type</key>
								<string>Color3</string>
								<key>value</key>
								<array>
									<integer>255</integer>
									<integer>255</integer>
									<integer>255</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>displayFrame</string>
								<key>type</key>
								<string>SpriteFrame</string>
								<key>value</key>
								<array>
									<string>钟表_指针动画.plist</string>
									<string>钟表_指针动画_图标_指针.png</string>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>useMaterial</string>
								<key>type</key>
								<string>Check</string>
								<key>value</key>
								<false/>
							</dict>
							<dict>
								<key>name</key>
								<string>blendFunc</string>
								<key>type</key>
								<string>Blendmode</string>
								<key>value</key>
								<array>
									<integer>1</integer>
									<integer>771</integer>
								</array>
							</dict>
						</array>
						<key>seqExpanded</key>
						<false/>
						<key>uniqueNodeId</key>
						<integer>608755280</integer>
					</dict>
					<dict>
						<key>animatedProperties</key>
						<dict/>
						<key>baseClass</key>
						<string>CCLabelPlus</string>
						<key>children</key>
						<array/>
						<key>customClass</key>
						<string></string>
						<key>customProperties</key>
						<array/>
						<key>displayName</key>
						<string>CCLabelPlus</string>
						<key>expand</key>
						<false/>
						<key>hidden</key>
						<false/>
						<key>locked</key>
						<false/>
						<key>memberVarAssignmentName</key>
						<string></string>
						<key>memberVarAssignmentType</key>
						<integer>0</integer>
						<key>nodeColorTag</key>
						<integer>0</integer>
						<key>properties</key>
						<array>
							<dict>
								<key>name</key>
								<string>position</string>
								<key>type</key>
								<string>Position</string>
								<key>value</key>
								<array>
									<real>60.0</real>
									<real>-26.0000153</real>
									<integer>0</integer>
									<integer>0</integer>
									<integer>0</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>opacity</string>
								<key>type</key>
								<string>Byte</string>
								<key>value</key>
								<integer>255</integer>
							</dict>
							<dict>
								<key>name</key>
								<string>labelConfig</string>
								<key>type</key>
								<string>LabelConfig</string>
								<key>value</key>
								<array>
									<dict/>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>blendFunc</string>
								<key>type</key>
								<string>Blendmode</string>
								<key>value</key>
								<array>
									<integer>1</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>dimensions</string>
								<key>type</key>
								<string>Size</string>
								<key>value</key>
								<array>
									<integer>0</integer>
									<integer>0</integer>
									<integer>0</integer>
									<integer>0</integer>
									<false/>
									<false/>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>string</string>
								<key>type</key>
								<string>Text</string>
								<key>value</key>
								<string>11:59</string>
							</dict>
							<dict>
								<key>name</key>
								<string>localization</string>
								<key>type</key>
								<string>Localization</string>
								<key>value</key>
								<array>
									<false/>
									<false/>
									<string></string>
									<string>11:59</string>
								</array>
							</dict>
						</array>
						<key>seqExpanded</key>
						<false/>
						<key>uniqueNodeId</key>
						<integer>740494450</integer>
					</dict>
				</array>
				<key>customClass</key>
				<string></string>
				<key>customProperties</key>
				<array/>
				<key>displayName</key>
				<string>进行中</string>
				<key>expand</key>
				<true/>
				<key>hidden</key>
				<false/>
				<key>locked</key>
				<false/>
				<key>memberVarAssignmentName</key>
				<string></string>
				<key>memberVarAssignmentType</key>
				<integer>0</integer>
				<key>nodeColorTag</key>
				<integer>0</integer>
				<key>properties</key>
				<array>
					<dict>
						<key>name</key>
						<string>visible</string>
						<key>type</key>
						<string>Check</string>
						<key>value</key>
						<false/>
					</dict>
					<dict>
						<key>name</key>
						<string>position</string>
						<key>type</key>
						<string>Position</string>
						<key>value</key>
						<array>
							<integer>0</integer>
							<integer>0</integer>
							<integer>0</integer>
							<integer>0</integer>
							<integer>0</integer>
						</array>
					</dict>
					<dict>
						<key>name</key>
						<string>contentSize</string>
						<key>type</key>
						<string>Size</string>
						<key>value</key>
						<array>
							<string>0</string>
							<integer>0</integer>
							<integer>0</integer>
							<integer>0</integer>
							<false/>
							<false/>
						</array>
					</dict>
					<dict>
						<key>name</key>
						<string>opacity</string>
						<key>type</key>
						<string>Byte</string>
						<key>value</key>
						<integer>255</integer>
					</dict>
					<dict>
						<key>name</key>
						<string>color</string>
						<key>type</key>
						<string>Color3</string>
						<key>value</key>
						<array>
							<integer>255</integer>
							<integer>255</integer>
							<integer>255</integer>
						</array>
					</dict>
				</array>
				<key>seqExpanded</key>
				<true/>
				<key>uniqueNodeId</key>
				<integer>129854574</integer>
			</dict>
			<dict>
				<key>animatedProperties</key>
				<dict>
					<key>1</key>
					<dict>
						<key>visible</key>
						<dict>
							<key>keyframes</key>
							<array>
								<dict>
									<key>easing</key>
									<dict>
										<key>type</key>
										<integer>0</integer>
									</dict>
									<key>name</key>
									<string>visible</string>
									<key>pathValues</key>
									<array/>
									<key>time</key>
									<real>0.0</real>
									<key>type</key>
									<integer>1</integer>
									<key>value</key>
									<true/>
								</dict>
								<dict>
									<key>easing</key>
									<dict>
										<key>type</key>
										<integer>0</integer>
									</dict>
									<key>name</key>
									<string>visible</string>
									<key>pathValues</key>
									<array/>
									<key>time</key>
									<real>0.0333333</real>
									<key>type</key>
									<integer>1</integer>
									<key>value</key>
									<true/>
								</dict>
							</array>
							<key>name</key>
							<string>visible</string>
							<key>type</key>
							<integer>1</integer>
						</dict>
					</dict>
				</dict>
				<key>baseClass</key>
				<string>CCNode</string>
				<key>children</key>
				<array>
					<dict>
						<key>animatedProperties</key>
						<dict/>
						<key>baseClass</key>
						<string>CCScale9Sprite</string>
						<key>children</key>
						<array/>
						<key>customClass</key>
						<string></string>
						<key>customProperties</key>
						<array/>
						<key>displayName</key>
						<string>时效组_底板右</string>
						<key>expand</key>
						<true/>
						<key>hidden</key>
						<false/>
						<key>locked</key>
						<false/>
						<key>memberVarAssignmentName</key>
						<string></string>
						<key>memberVarAssignmentType</key>
						<integer>0</integer>
						<key>nodeColorTag</key>
						<integer>0</integer>
						<key>properties</key>
						<array>
							<dict>
								<key>name</key>
								<string>position</string>
								<key>type</key>
								<string>Position</string>
								<key>value</key>
								<array>
									<real>0.0</real>
									<real>0.0</real>
									<integer>0</integer>
									<integer>2</integer>
									<integer>2</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>anchorPoint</string>
								<key>type</key>
								<string>Point</string>
								<key>value</key>
								<array>
									<real>1.0</real>
									<real>0.5</real>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>scale</string>
								<key>type</key>
								<string>ScaleLock</string>
								<key>value</key>
								<array>
									<real>-1.0</real>
									<real>1.0</real>
									<false/>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>opacity</string>
								<key>type</key>
								<string>Byte</string>
								<key>value</key>
								<integer>255</integer>
							</dict>
							<dict>
								<key>name</key>
								<string>color</string>
								<key>type</key>
								<string>Color3</string>
								<key>value</key>
								<array>
									<integer>255</integer>
									<integer>255</integer>
									<integer>255</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>spriteFrame</string>
								<key>type</key>
								<string>SpriteFrame</string>
								<key>value</key>
								<array>
									<string>钟表_指针动画.plist</string>
									<string>钟表_指针动画_时效组_底板.png</string>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>preferedSize</string>
								<key>type</key>
								<string>Size</string>
								<key>value</key>
								<array>
									<real>158.0</real>
									<real>95.0</real>
									<integer>0</integer>
									<integer>0</integer>
									<false/>
									<false/>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>insetLeft</string>
								<key>type</key>
								<string>Float</string>
								<key>value</key>
								<real>55.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>insetTop</string>
								<key>type</key>
								<string>Float</string>
								<key>value</key>
								<real>5.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>insetRight</string>
								<key>type</key>
								<string>Float</string>
								<key>value</key>
								<real>55.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>insetBottom</string>
								<key>type</key>
								<string>Float</string>
								<key>value</key>
								<real>5.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>previewInset</string>
								<key>type</key>
								<string>Check</string>
								<key>value</key>
								<true/>
							</dict>
							<dict>
								<key>name</key>
								<string>copyFlipXDir</string>
								<key>type</key>
								<string>ToggleGroup</string>
								<key>value</key>
								<integer>1</integer>
							</dict>
						</array>
						<key>seqExpanded</key>
						<false/>
						<key>uniqueNodeId</key>
						<integer>828812879</integer>
					</dict>
					<dict>
						<key>animatedProperties</key>
						<dict/>
						<key>baseClass</key>
						<string>CCScale9Sprite</string>
						<key>children</key>
						<array/>
						<key>customClass</key>
						<string></string>
						<key>customProperties</key>
						<array/>
						<key>displayName</key>
						<string>时效组_底板左</string>
						<key>expand</key>
						<true/>
						<key>hidden</key>
						<true/>
						<key>locked</key>
						<false/>
						<key>memberVarAssignmentName</key>
						<string></string>
						<key>memberVarAssignmentType</key>
						<integer>0</integer>
						<key>nodeColorTag</key>
						<integer>0</integer>
						<key>properties</key>
						<array>
							<dict>
								<key>name</key>
								<string>visible</string>
								<key>type</key>
								<string>Check</string>
								<key>value</key>
								<true/>
							</dict>
							<dict>
								<key>name</key>
								<string>position</string>
								<key>type</key>
								<string>Position</string>
								<key>value</key>
								<array>
									<real>0.0</real>
									<real>0.0</real>
									<integer>0</integer>
									<integer>2</integer>
									<integer>2</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>anchorPoint</string>
								<key>type</key>
								<string>Point</string>
								<key>value</key>
								<array>
									<real>1.0</real>
									<real>0.5</real>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>opacity</string>
								<key>type</key>
								<string>Byte</string>
								<key>value</key>
								<integer>255</integer>
							</dict>
							<dict>
								<key>name</key>
								<string>color</string>
								<key>type</key>
								<string>Color3</string>
								<key>value</key>
								<array>
									<integer>255</integer>
									<integer>255</integer>
									<integer>255</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>spriteFrame</string>
								<key>type</key>
								<string>SpriteFrame</string>
								<key>value</key>
								<array>
									<string>钟表_指针动画.plist</string>
									<string>钟表_指针动画_时效组_底板.png</string>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>preferedSize</string>
								<key>type</key>
								<string>Size</string>
								<key>value</key>
								<array>
									<real>158.0</real>
									<real>95.0</real>
									<integer>0</integer>
									<integer>0</integer>
									<false/>
									<false/>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>insetLeft</string>
								<key>type</key>
								<string>Float</string>
								<key>value</key>
								<real>55.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>insetTop</string>
								<key>type</key>
								<string>Float</string>
								<key>value</key>
								<real>5.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>insetRight</string>
								<key>type</key>
								<string>Float</string>
								<key>value</key>
								<real>1.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>insetBottom</string>
								<key>type</key>
								<string>Float</string>
								<key>value</key>
								<real>5.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>previewInset</string>
								<key>type</key>
								<string>Check</string>
								<key>value</key>
								<true/>
							</dict>
						</array>
						<key>seqExpanded</key>
						<true/>
						<key>uniqueNodeId</key>
						<integer>721970174</integer>
					</dict>
					<dict>
						<key>animatedProperties</key>
						<dict>
							<key>0</key>
							<dict>
								<key>scale</key>
								<dict>
									<key>keyframes</key>
									<array>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>1</integer>
											</dict>
											<key>name</key>
											<string>scale</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>4.2666669</real>
											<key>type</key>
											<integer>4</integer>
											<key>value</key>
											<array>
												<real>1.0</real>
												<real>1.0</real>
											</array>
										</dict>
									</array>
									<key>name</key>
									<string>scale</string>
									<key>type</key>
									<integer>4</integer>
								</dict>
							</dict>
						</dict>
						<key>baseClass</key>
						<string>CCSprite</string>
						<key>children</key>
						<array/>
						<key>customClass</key>
						<string></string>
						<key>customProperties</key>
						<array/>
						<key>displayName</key>
						<string>图标_时钟</string>
						<key>expand</key>
						<false/>
						<key>hidden</key>
						<false/>
						<key>locked</key>
						<false/>
						<key>memberVarAssignmentName</key>
						<string></string>
						<key>memberVarAssignmentType</key>
						<integer>0</integer>
						<key>nodeColorTag</key>
						<integer>0</integer>
						<key>properties</key>
						<array>
							<dict>
								<key>name</key>
								<string>position</string>
								<key>type</key>
								<string>Position</string>
								<key>value</key>
								<array>
									<real>0.0</real>
									<real>0.0</real>
									<integer>0</integer>
									<integer>0</integer>
									<integer>0</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>scale</string>
								<key>type</key>
								<string>ScaleLock</string>
								<key>value</key>
								<array>
									<real>1.0</real>
									<real>1.0</real>
									<false/>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>opacity</string>
								<key>type</key>
								<string>Byte</string>
								<key>value</key>
								<integer>255</integer>
							</dict>
							<dict>
								<key>name</key>
								<string>color</string>
								<key>type</key>
								<string>Color3</string>
								<key>value</key>
								<array>
									<integer>255</integer>
									<integer>255</integer>
									<integer>255</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>displayFrame</string>
								<key>type</key>
								<string>SpriteFrame</string>
								<key>value</key>
								<array>
									<string>钟表_指针动画.plist</string>
									<string>钟表_指针动画_图标_时钟.png</string>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>useMaterial</string>
								<key>type</key>
								<string>Check</string>
								<key>value</key>
								<false/>
							</dict>
							<dict>
								<key>name</key>
								<string>blendFunc</string>
								<key>type</key>
								<string>Blendmode</string>
								<key>value</key>
								<array>
									<integer>1</integer>
									<integer>771</integer>
								</array>
							</dict>
						</array>
						<key>seqExpanded</key>
						<false/>
						<key>uniqueNodeId</key>
						<integer>826239558</integer>
					</dict>
					<dict>
						<key>animatedProperties</key>
						<dict>
							<key>0</key>
							<dict>
								<key>rotation</key>
								<dict>
									<key>keyframes</key>
									<array>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>1</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>0.0</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>0.0</real>
										</dict>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>12</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>0.0</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>0.0</real>
										</dict>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>1</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>0.5</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>90.0</real>
										</dict>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>12</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>1.0666667</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>90.0</real>
										</dict>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>1</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>1.6</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>180.0</real>
										</dict>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>12</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>2.2</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>180.0</real>
										</dict>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>1</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>2.7</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>270.0</real>
										</dict>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>12</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>3.2333333</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>270.0</real>
										</dict>
										<dict>
											<key>easing</key>
											<dict>
												<key>type</key>
												<integer>1</integer>
											</dict>
											<key>name</key>
											<string>rotation</string>
											<key>pathValues</key>
											<array/>
											<key>time</key>
											<real>3.8</real>
											<key>type</key>
											<integer>2</integer>
											<key>value</key>
											<real>360.0</real>
										</dict>
									</array>
									<key>name</key>
									<string>rotation</string>
									<key>type</key>
									<integer>2</integer>
								</dict>
							</dict>
						</dict>
						<key>baseClass</key>
						<string>CCSprite</string>
						<key>children</key>
						<array/>
						<key>customClass</key>
						<string></string>
						<key>customProperties</key>
						<array/>
						<key>displayName</key>
						<string>指针</string>
						<key>expand</key>
						<false/>
						<key>hidden</key>
						<false/>
						<key>locked</key>
						<false/>
						<key>memberVarAssignmentName</key>
						<string></string>
						<key>memberVarAssignmentType</key>
						<integer>0</integer>
						<key>nodeColorTag</key>
						<integer>0</integer>
						<key>properties</key>
						<array>
							<dict>
								<key>name</key>
								<string>visible</string>
								<key>type</key>
								<string>Check</string>
								<key>value</key>
								<true/>
							</dict>
							<dict>
								<key>name</key>
								<string>position</string>
								<key>type</key>
								<string>Position</string>
								<key>value</key>
								<array>
									<real>-2.0</real>
									<real>-6.0</real>
									<integer>0</integer>
									<integer>0</integer>
									<integer>0</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>anchorPoint</string>
								<key>type</key>
								<string>Point</string>
								<key>value</key>
								<array>
									<real>0.5</real>
									<real>0.3</real>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>rotation</string>
								<key>type</key>
								<string>Degrees</string>
								<key>value</key>
								<real>0.0</real>
							</dict>
							<dict>
								<key>name</key>
								<string>opacity</string>
								<key>type</key>
								<string>Byte</string>
								<key>value</key>
								<integer>255</integer>
							</dict>
							<dict>
								<key>name</key>
								<string>color</string>
								<key>type</key>
								<string>Color3</string>
								<key>value</key>
								<array>
									<integer>255</integer>
									<integer>255</integer>
									<integer>255</integer>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>displayFrame</string>
								<key>type</key>
								<string>SpriteFrame</string>
								<key>value</key>
								<array>
									<string>钟表_指针动画.plist</string>
									<string>钟表_指针动画_图标_指针.png</string>
								</array>
							</dict>
							<dict>
								<key>name</key>
								<string>useMaterial</string>
								<key>type</key>
								<string>Check</string>
								<key>value</key>
								<false/>
							</dict>
							<dict>
								<key>name</key>
								<string>blendFunc</string>
								<key>type</key>
								<string>Blendmode</string>
								<key>value</key>
								<array>
									<integer>1</integer>
									<integer>771</integer>
								</array>
							</dict>
						</array>
						<key>seqExpanded</key>
						<false/>
						<key>uniqueNodeId</key>
						<integer>615015333</integer>
					</dict>
				</array>
				<key>customClass</key>
				<string></string>
				<key>customProperties</key>
				<array/>
				<key>displayName</key>
				<string>已结束</string>
				<key>expand</key>
				<true/>
				<key>hidden</key>
				<false/>
				<key>locked</key>
				<false/>
				<key>memberVarAssignmentName</key>
				<string></string>
				<key>memberVarAssignmentType</key>
				<integer>0</integer>
				<key>nodeColorTag</key>
				<integer>0</integer>
				<key>properties</key>
				<array>
					<dict>
						<key>name</key>
						<string>visible</string>
						<key>type</key>
						<string>Check</string>
						<key>value</key>
						<false/>
					</dict>
					<dict>
						<key>name</key>
						<string>position</string>
						<key>type</key>
						<string>Position</string>
						<key>value</key>
						<array>
							<integer>0</integer>
							<integer>0</integer>
							<integer>0</integer>
							<integer>0</integer>
							<integer>0</integer>
						</array>
					</dict>
					<dict>
						<key>name</key>
						<string>contentSize</string>
						<key>type</key>
						<string>Size</string>
						<key>value</key>
						<array>
							<string>0</string>
							<integer>0</integer>
							<integer>0</integer>
							<integer>0</integer>
							<false/>
							<false/>
						</array>
					</dict>
					<dict>
						<key>name</key>
						<string>opacity</string>
						<key>type</key>
						<string>Byte</string>
						<key>value</key>
						<integer>255</integer>
					</dict>
					<dict>
						<key>name</key>
						<string>color</string>
						<key>type</key>
						<string>Color3</string>
						<key>value</key>
						<array>
							<integer>255</integer>
							<integer>255</integer>
							<integer>255</integer>
						</array>
					</dict>
				</array>
				<key>seqExpanded</key>
				<true/>
				<key>uniqueNodeId</key>
				<integer>648396642</integer>
			</dict>
			<dict>
				<key>animatedProperties</key>
				<dict>
					<key>1</key>
					<dict>
						<key>visible</key>
						<dict>
							<key>keyframes</key>
							<array>
								<dict>
									<key>easing</key>
									<dict>
										<key>type</key>
										<integer>0</integer>
									</dict>
									<key>name</key>
									<string>visible</string>
									<key>pathValues</key>
									<array/>
									<key>time</key>
									<real>0.0</real>
									<key>type</key>
									<integer>1</integer>
									<key>value</key>
									<true/>
								</dict>
							</array>
							<key>name</key>
							<string>visible</string>
							<key>type</key>
							<integer>1</integer>
						</dict>
					</dict>
				</dict>
				<key>baseClass</key>
				<string>CCLabelPlus</string>
				<key>children</key>
				<array/>
				<key>customClass</key>
				<string></string>
				<key>customProperties</key>
				<array/>
				<key>displayName</key>
				<string>CCLabelPlus</string>
				<key>expand</key>
				<false/>
				<key>hidden</key>
				<false/>
				<key>locked</key>
				<false/>
				<key>memberVarAssignmentName</key>
				<string></string>
				<key>memberVarAssignmentType</key>
				<integer>0</integer>
				<key>nodeColorTag</key>
				<integer>0</integer>
				<key>properties</key>
				<array>
					<dict>
						<key>name</key>
						<string>visible</string>
						<key>type</key>
						<string>Check</string>
						<key>value</key>
						<false/>
					</dict>
					<dict>
						<key>name</key>
						<string>position</string>
						<key>type</key>
						<string>Position</string>
						<key>value</key>
						<array>
							<real>92.999939</real>
							<real>-17.0</real>
							<integer>0</integer>
							<integer>0</integer>
							<integer>0</integer>
						</array>
					</dict>
					<dict>
						<key>name</key>
						<string>opacity</string>
						<key>type</key>
						<string>Byte</string>
						<key>value</key>
						<integer>255</integer>
					</dict>
					<dict>
						<key>name</key>
						<string>labelConfig</string>
						<key>type</key>
						<string>LabelConfig</string>
						<key>value</key>
						<array>
							<dict/>
						</array>
					</dict>
					<dict>
						<key>name</key>
						<string>blendFunc</string>
						<key>type</key>
						<string>Blendmode</string>
						<key>value</key>
						<array>
							<integer>1</integer>
						</array>
					</dict>
					<dict>
						<key>name</key>
						<string>dimensions</string>
						<key>type</key>
						<string>Size</string>
						<key>value</key>
						<array>
							<integer>0</integer>
							<integer>0</integer>
							<integer>0</integer>
							<integer>0</integer>
							<false/>
							<false/>
						</array>
					</dict>
					<dict>
						<key>name</key>
						<string>string</string>
						<key>type</key>
						<string>Text</string>
						<key>value</key>
						<string>finished</string>
					</dict>
					<dict>
						<key>name</key>
						<string>localization</string>
						<key>type</key>
						<string>Localization</string>
						<key>value</key>
						<array>
							<false/>
							<false/>
							<string></string>
							<string>finished</string>
						</array>
					</dict>
				</array>
				<key>seqExpanded</key>
				<false/>
				<key>uniqueNodeId</key>
				<integer>170105069</integer>
			</dict>
		</array>
		<key>customClass</key>
		<string></string>
		<key>customProperties</key>
		<array/>
		<key>displayName</key>
		<string>CCNode</string>
		<key>expand</key>
		<true/>
		<key>hidden</key>
		<false/>
		<key>locked</key>
		<false/>
		<key>memberVarAssignmentName</key>
		<string></string>
		<key>memberVarAssignmentType</key>
		<integer>0</integer>
		<key>nodeColorTag</key>
		<integer>0</integer>
		<key>properties</key>
		<array>
			<dict>
				<key>name</key>
				<string>position</string>
				<key>type</key>
				<string>Position</string>
				<key>value</key>
				<array>
					<real>0.0</real>
					<real>0.0</real>
					<integer>0</integer>
					<integer>0</integer>
					<integer>0</integer>
				</array>
			</dict>
		</array>
		<key>seqExpanded</key>
		<false/>
		<key>uniqueNodeId</key>
		<integer>194647785</integer>
	</dict>
	<key>rebolt</key>
	<dict>
		<key>isRebolted</key>
		<false/>
		<key>redInfos</key>
		<dict/>
	</dict>
	<key>referenceImgNode</key>
	<dict>
		<key>animatedProperties</key>
		<dict/>
		<key>baseClass</key>
		<string>ReferenceImageNode</string>
		<key>children</key>
		<array/>
		<key>customClass</key>
		<string></string>
		<key>customProperties</key>
		<array/>
		<key>displayName</key>
		<string>Reference Image</string>
		<key>expand</key>
		<false/>
		<key>hidden</key>
		<true/>
		<key>locked</key>
		<false/>
		<key>memberVarAssignmentName</key>
		<string></string>
		<key>memberVarAssignmentType</key>
		<integer>0</integer>
		<key>nodeColorTag</key>
		<integer>0</integer>
		<key>properties</key>
		<array>
			<dict>
				<key>name</key>
				<string>visible</string>
				<key>type</key>
				<string>Check</string>
				<key>value</key>
				<false/>
			</dict>
			<dict>
				<key>name</key>
				<string>position</string>
				<key>type</key>
				<string>Position</string>
				<key>value</key>
				<array>
					<integer>0</integer>
					<integer>0</integer>
					<integer>0</integer>
					<integer>0</integer>
					<integer>0</integer>
				</array>
			</dict>
			<dict>
				<key>name</key>
				<string>contentSize</string>
				<key>type</key>
				<string>Size</string>
				<key>value</key>
				<array>
					<string>0</string>
					<integer>0</integer>
					<integer>0</integer>
					<integer>0</integer>
					<false/>
					<false/>
				</array>
			</dict>
			<dict>
				<key>name</key>
				<string>opacity</string>
				<key>type</key>
				<string>Byte</string>
				<key>value</key>
				<integer>255</integer>
			</dict>
			<dict>
				<key>name</key>
				<string>color</string>
				<key>type</key>
				<string>Color3</string>
				<key>value</key>
				<array>
					<integer>255</integer>
					<integer>255</integer>
					<integer>255</integer>
				</array>
			</dict>
			<dict>
				<key>name</key>
				<string>displayFrame</string>
				<key>type</key>
				<string>ReferenceSpriteFrame</string>
				<key>value</key>
				<array>
					<string></string>
					<string></string>
				</array>
			</dict>
		</array>
		<key>seqExpanded</key>
		<false/>
		<key>uniqueNodeId</key>
		<integer>687923575</integer>
	</dict>
	<key>resolutions</key>
	<array>
		<dict>
			<key>additionalScale</key>
			<real>2.0</real>
			<key>centeredOrigin</key>
			<false/>
			<key>height</key>
			<integer>0</integer>
			<key>mainScale</key>
			<real>2.0</real>
			<key>name</key>
			<string>1280x720</string>
			<key>resourceScale</key>
			<real>2.0</real>
			<key>scale</key>
			<real>2.0</real>
			<key>width</key>
			<integer>0</integer>
		</dict>
	</array>
	<key>sequences</key>
	<array>
		<dict>
			<key>autoPlay</key>
			<true/>
			<key>callbackChannel</key>
			<dict>
				<key>keyframes</key>
				<array/>
				<key>name</key>
				<string></string>
				<key>type</key>
				<integer>0</integer>
			</dict>
			<key>chainedSequenceId</key>
			<integer>0</integer>
			<key>length</key>
			<real>4.2666669</real>
			<key>name</key>
			<string>进行中</string>
			<key>offset</key>
			<real>0.0</real>
			<key>playSpeed</key>
			<real>1.0</real>
			<key>position</key>
			<real>0.0</real>
			<key>resolution</key>
			<real>30.0</real>
			<key>scale</key>
			<real>128.0</real>
			<key>sequenceId</key>
			<integer>0</integer>
			<key>shake2Channel</key>
			<dict>
				<key>keyframes</key>
				<array/>
				<key>name</key>
				<string></string>
				<key>type</key>
				<integer>0</integer>
			</dict>
			<key>shakeChannel</key>
			<dict>
				<key>keyframes</key>
				<array/>
				<key>name</key>
				<string></string>
				<key>type</key>
				<integer>0</integer>
			</dict>
			<key>soundChannel</key>
			<dict>
				<key>keyframes</key>
				<array/>
				<key>name</key>
				<string></string>
				<key>type</key>
				<integer>0</integer>
			</dict>
			<key>timelineEndPlay</key>
			<real>4.2666669</real>
			<key>timelineStartPlay</key>
			<real>0.0</real>
			<key>wiseChannel</key>
			<dict>
				<key>keyframes</key>
				<array/>
				<key>name</key>
				<string></string>
				<key>type</key>
				<integer>0</integer>
			</dict>
		</dict>
		<dict>
			<key>autoPlay</key>
			<false/>
			<key>callbackChannel</key>
			<dict>
				<key>keyframes</key>
				<array/>
				<key>name</key>
				<string></string>
				<key>type</key>
				<integer>0</integer>
			</dict>
			<key>chainedSequenceId</key>
			<integer>-1</integer>
			<key>length</key>
			<real>0.0333333</real>
			<key>name</key>
			<string>已结束</string>
			<key>offset</key>
			<real>0.0</real>
			<key>playSpeed</key>
			<real>1.0</real>
			<key>position</key>
			<real>0.0</real>
			<key>resolution</key>
			<real>30.0</real>
			<key>scale</key>
			<real>576.0</real>
			<key>sequenceId</key>
			<integer>1</integer>
			<key>shake2Channel</key>
			<dict>
				<key>keyframes</key>
				<array/>
				<key>name</key>
				<string></string>
				<key>type</key>
				<integer>0</integer>
			</dict>
			<key>shakeChannel</key>
			<dict>
				<key>keyframes</key>
				<array/>
				<key>name</key>
				<string></string>
				<key>type</key>
				<integer>0</integer>
			</dict>
			<key>soundChannel</key>
			<dict>
				<key>keyframes</key>
				<array/>
				<key>name</key>
				<string></string>
				<key>type</key>
				<integer>0</integer>
			</dict>
			<key>timelineEndPlay</key>
			<real>0.0333333</real>
			<key>timelineStartPlay</key>
			<real>0.0</real>
			<key>wiseChannel</key>
			<dict>
				<key>keyframes</key>
				<array/>
				<key>name</key>
				<string></string>
				<key>type</key>
				<integer>0</integer>
			</dict>
		</dict>
	</array>
	<key>stageBorder</key>
	<integer>0</integer>
</dict>
</plist>
